"""Export Playwright storage-state cookies to a Netscape cookie file for yt-dlp.

yt-dlp needs Skool's auth cookies to fetch Skool-native / Mux signed streams.
We translate the cookies array from ``storage_state.json`` into the Netscape
``cookies.txt`` format that yt-dlp's ``--cookies`` flag understands.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


def write_cookie_file(storage_state_path: Path, dest: Path) -> Optional[Path]:
    """Write a Netscape cookie file from a Playwright storage state. Returns the
    destination path, or None if there were no cookies to export."""
    if not storage_state_path.exists():
        return None
    try:
        state = json.loads(storage_state_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None

    cookies = state.get("cookies") or []
    if not cookies:
        return None

    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by skool-extractor", ""]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        # expires: Playwright uses -1 for session cookies; yt-dlp wants an int
        expires = int(c.get("expires", 0) or 0)
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, include_sub, path, secure,
                                str(expires), name, value]))

    dest.write_text("\n".join(lines) + "\n")
    return dest
